sudo: false

language: java
jdk: oraclejdk8

before_install:
  - unset _JAVA_OPTIONS

jobs:
  include:
# starter
    - stage: starter
      name: "Jupiter Starter Sample: Gradle & Java"
      env: TOOL='Gradle'
      script: cd $TRAVIS_BUILD_DIR && ./gradlew test --console plain
